"""initial_subscription_schema

Revision ID: 1eda6ee3e97c
Revises: 
Create Date: 2026-08-18 15:02:42.766525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eda6ee3e97c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subscription_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('notification_uuid', sa.String(length=100), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('original_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_events_notification_uuid'), 'subscription_events', ['notification_uuid'], unique=True)
    op.create_index(op.f('ix_subscription_events_original_transaction_id'), 'subscription_events', ['original_transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('app_account_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_app_account_token'), 'users', ['app_account_token'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('original_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('latest_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('app_account_token', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew_status', sa.Boolean(), nullable=False),
    sa.Column('is_in_billing_retry', sa.Boolean(), nullable=False),
    sa.Column('revocation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_app_account_token'), 'subscriptions', ['app_account_token'], unique=False)
    op.create_index(op.f('ix_subscriptions_original_transaction_id'), 'subscriptions', ['original_transaction_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('original_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_original_transaction_id'), 'transactions', ['original_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_subscription_id'), 'transactions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_subscription_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_original_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_original_transaction_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_app_account_token'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_app_account_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_events_original_transaction_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_notification_uuid'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_table('app_configs')
    # ### end Alembic commands ###
